name: youdo
version: '3.8'

services:
  db:
    container_name: 'you-do-db'
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - youdo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 3

  api:
    container_name: 'you-do-api'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7065:7065"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7065
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - youdo-network

networks:
  youdo-network:
    driver: bridge

volumes:
  postgres_data: