name: CD Production

# Este workflow só será executado após o ci-production ter sido concluído com sucesso
on:
  workflow_run:
    workflows: ["CI Production"]  # Nome do workflow ci-production
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    # Só executa se o workflow anterior foi bem-sucedido
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
      with:
        # Precisamos fazer checkout do código que foi testado no CI
        ref: ${{ github.event.workflow_run.head_sha }}
      
    - name: Login into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and Push image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: ./src/backend
        file: ./src/backend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/youdo-api:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/youdo-api:${{ github.event.workflow_run.head_sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/youdo-api:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/youdo-api:buildcache,mode=max
