name: CI Development

on:
  push:
    branches: [ "develop" ]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: src

  restore-dependencies:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: src
          path: src

      - name: Restore dependencies
        run: dotnet restore src

  build:
    runs-on: ubuntu-latest
    needs: restore-dependencies
    env:
      SECRETKEYTEST: ${{ secrets.SECRETKEYTEST }}

    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: src
          path: src

      - name: Build solution
        run: dotnet build src --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: src
          path: src

      - name: Run tests
        run: dotnet test src --no-build --verbosity normal
    
