name: CI Development

on:
  push:
    branches: [ "develop" ]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: src

  restore-dependencies-and-build:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: src
          path: src

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore src/YouDo.sln

      - name: Build solution
        run: dotnet build src/YouDo.sln

      - name: Checkout code formatting
        run: dotnet format --verify-no-changes

      - name: Upload restored files
        uses: actions/upload-artifact@v4
        with:
          name: restored-src
          path: src

  test:
    runs-on: ubuntu-latest
    needs: restore-dependencies-and-build
    env: 
      SECRETKEYTEST: ${{ secrets.SECRETKEYTEST }}

    steps:
      - name: Download restored files
        uses: actions/download-artifact@v4
        with:
          name: restored-src
          path: src

      - name: Run tests
        run: dotnet test src/YouDo.sln --no-build --verbosity normal