name: CI Development

on:
  push:
    branches: [ "develop" ]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: src
          path: src

  restore-dependencies:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: src
          path: src

      - name: Restore dependencies
        run: dotnet restore src/YouDo.sln  # Substitua pelo nome do seu arquivo .sln

      - name: List files after restore
        run: ls -R src

      - name: Upload restored files
        uses: actions/upload-artifact@v4
        with:
          name: restored-src
          path: src

  build:
    runs-on: ubuntu-latest
    needs: restore-dependencies

    steps:
      - name: Download restored files
        uses: actions/download-artifact@v4
        with:
          name: restored-src
          path: src

      - name: List files after download
        run: ls -R src

      - name: Verify restored files
        run: ls -R src/**/obj/project.assets.json

      - name: Build solution
        run: dotnet build src/YouDo.sln --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download restored files
        uses: actions/download-artifact@v4
        with:
          name: restored-src
          path: src

      - name: Run tests
        run: dotnet test src/YouDo.sln --no-build --verbosity normal